// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArrowIcon: typeof import('./src/components/assets/icons/ArrowIcon.vue')['default']
    CopyIcon: typeof import('./src/components/assets/icons/CopyIcon.vue')['default']
    GithubIcon: typeof import('./src/components/assets/icons/GithubIcon.vue')['default']
    IconBase: typeof import('./src/components/base/IconBase.vue')['default']
    IntroductionSection: typeof import('./src/components/section/IntroductionSection.vue')['default']
    LinkedinIcon: typeof import('./src/components/assets/icons/LinkedinIcon.vue')['default']
    LogoBase: typeof import('./src/components/base/LogoBase.vue')['default']
    MainLogo: typeof import('./src/components/assets/logo/MainLogo.vue')['default']
    MaltIcon: typeof import('./src/components/assets/icons/MaltIcon.vue')['default']
    TwitterIcon: typeof import('./src/components/assets/icons/TwitterIcon.vue')['default']
  }
}
